services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: baifa-ui:local
    container_name: baifa-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_PUBLIC_API_BASE=http://localhost:8000/api
    networks:
      - baifa-api_baifa_network

networks:
  baifa-api_baifa_network:
    external: true
